---
- hosts: all
  tasks:
    - name: Stop service httpd, if running
      service:
        name: httpd
        state: stopped

    - name: Start service httpd, if not running
      service:
         name: httpd
         state: started

